---
title: "dashboard"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: journal
---

```{r setup, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(viridis)
library(p8105.datasets)
library(plotly)
```

```{r}
data("instacart")
```

```{r, echo = FALSE}
set.seed(1)

instacart = 
    instacart %>%
sample_n(5000)

instacart %>%
    mutate(text_label = str_c("Days Since Prior Order", days_since_prior_order)) %>%
    plot_ly (
        x = ~order_hour_of_day, y = ~days_since_prior_order, type = "scatter", mode = "markers", color = "Set2", text = ~text_label, alpha = 0.5)

instacart_scatter = 
instacart %>%
    mutate(text_label = str_c("Order Hour of Day", order_hour_of_day)) %>%
    plot_ly (
        x = ~days_since_prior_order, y = ~order_hour_of_day, type = "scatter", mode = "markers", color = "Set2", text = ~text_label, alpha = 0.5)
```

# Top 10 Products and Associated Frequencies 
```{r, echo = FALSE}
instacart_bar = 
instacart %>%
    count(aisle) %>%
    mutate(aisle = fct_reorder(aisle, n)) %>%
    top_n(10) %>%
    plot_ly (
        x = ~aisle, y = ~n, type = "bar", color = ~aisle) %>%
  layout(
      title = "Top 10 Products and Associated Frequencies", 
      xaxis = list(title = "Aisle Name"), 
      yaxis = list(title = "Frequency")
  )

instacart_bar
```

# Top 15 Departments and Corresponding Order Hour of the Day 
```{r, echo = FALSE}
new_instacart =
  instacart %>% 
  count(department, sort = TRUE) %>% 
  top_n(15) 

inner_join(instacart, new_instacart, by = "department") %>% 
  mutate(department = fct_reorder(department, order_hour_of_day)) %>% 
  plot_ly(y = ~order_hour_of_day, color = ~department, type = "box",
          colors = "Set2") %>%
  layout(
      title = "Top 15 Departments and Corresponding Order Hour of the Day", 
      xaxis = list(title = "Department"), 
      yaxis = list(title = "Order Hour of the Day")
  )
```

```{r}

```

