---
title: "My Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
data("instacart")

set.seed(1)

instacart = 
    instacart %>%
sample_n(5000)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Plot 1: 

```{r, echo = FALSE, message = FALSE, warning = FALSE}
  instacart %>% 
  count(days_since_prior_order, sort = TRUE) %>% 
  plot_ly(x = ~days_since_prior_order, y = ~n,
          type = "scatter", mode = "markers", color = ~days_since_prior_order, alpha = 0.5) %>%
   layout(
      title = "Days since Last Order and Customer Frequency", 
      xaxis = list(title = "Days Since Prior Order"), 
      yaxis = list(title = "Customer Frequency")
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Plot 2: 

```{r, echo = FALSE, message = FALSE, warning = FALSE}
instacart %>%
    count(aisle) %>%
    mutate(aisle = fct_reorder(aisle, n)) %>%
    top_n(20) %>%
    plot_ly (
        x = ~aisle, y = ~n, type = "bar", color = ~aisle) %>%
  layout(
      title = "Top 20 Products and Associated Frequencies", 
      xaxis = list(title = "Aisle Name"), 
      yaxis = list(title = "Frequency")
  )
```

### Plot 3: 

```{r, echo = FALSE, message = FALSE, warning = FALSE}

new_instacart = instacart %>% 
  count(department, sort = TRUE) %>% 
  top_n(15) 

inner_join(instacart, new_instacart, by = "department") %>% 
  mutate(department = fct_reorder(department, order_hour_of_day)) %>% 
  plot_ly(y = ~order_hour_of_day, color = ~department, type = "box",
          colors = "Set2") %>%
  layout(
      title = "Top 15 Departments and Corresponding Order Hour of the Day", 
      xaxis = list(title = "Department"), 
      yaxis = list(title = "Hour of the Day")
  )
```
